# Automatically generated by https://github.com/rec/make_pyx/make_pyx.py
# from tada/signal/fade.h.
cdef extern from "<tada/signal/fade.h>" namespace "tada::Fade":
    cdef cppclass Type:
        pass

cdef extern from "<tada/signal/fade.h>" namespace "tada::Fade::Type":
    cdef Type linear
    cdef Type sqr
    cdef Type sqrt

cdef extern from "<tada/signal/fade.h>" namespace "tada":
    struct Fade:
        float begin, end
        Type type

cdef class _Fade(_Wrapper):
    cdef Fade _instance;

    TYPE_NAMES = 'linear', 'sqr', 'sqrt'

    def __cinit__(self):
        clearStruct(self._instance)

    def clear(self):
        clearStruct(self._instance)

    def __str__(self):
        return "(begin=%s, end=%s, type='%s')" % (
            self.begin, self.end, self.type)

    property begin:
        def __get__(self):
            return self._instance.begin
        def __set__(self, float x):
            self._instance.begin = x

    property end:
        def __get__(self):
            return self._instance.end
        def __set__(self, float x):
            self._instance.end = x

    property type:
        def __get__(self):
            return self.TYPE_NAMES[<int> self._instance.type]
        def __set__(self, object x):
            cdef uint8_t i
            if isinstance(x, str):
                i = self.TYPE_NAMES.index(x)
            else:
                i = <uint8_t> x
                if i >= len(self.TYPE_NAMES):
                    raise ValueError("Can't understand value " + str(i))
            self._instance.type = <Type>(i)
